export async function sendStepData(step, payload) {
  console.log("JSON SENT TO BACKEND:", {
    step,
    payload,
  });

  // MOCK RESPONSE (anggap dari backend ontology)
  return {
    decision: step < 4 ? "NEXT" : "STOP",
    explanation:
      "Decision generated by ontology-based clinical reasoning engine",
  };
}
